---
title: AneX Manual - Model 1.0.0 (Scratch)
author: Alec Larsen (via AneX)
date: now
date-format: "MMMM D YYYY - HH:mm:ss (z)"

format:
    html:
        code-fold: true
        title-block-banner: "#472745"
        title-block-banner-color: "#FFFFFF"

engine: jupyter
jupyter: python3

execute:
    include: false
    echo: false
    notebook: false
---

# Introduction
This document details the current functionalities, known limitations, and future plans for AneX.

## NOTE
This manual is currently incomplete. Expect frequent changes as new sections are written over the next several days.

## A 'Brief' History
AneX has been slowly built over the course of the last year, and will likely continue to slowly progress for the forseeable future as my working knowledge of statistics and modeling improves. While it originally began as an informal personal project, it has since evolved into a much more complicated system.

Beyond all other aspects, I'm treating AneX as a learning experience. As the major changes between different verions suggest, I am always looking for different ways to improve my statistical modeling and other related skills. With the current model to predict home goal differential intended to be temporary and having notable limitations, I have a clear goal to work towards at the moment.

### Era 1: Hockey Statistical Compiler (HSC)
In May of 2025, a few weeks away from the start of the Stanley Cup finals, I started, what was intended to be, a very short project. I hoped to build a model to produce a very rough estimate of the probability that the Edmonton Oilers would win the Stanley Cup.

Having used R extensively for an introductory statistics, I opted to use R for the main scaffolding. However, having also taken introductory mechaine learning earlier in the year, I was interested in using Python (specifically sklearn) to handle the training of basic supervised learning algorithms.

### Era 2: AneStat and Leafs Status Report
Though the results coming form HSC were very rough and far from polished, I saw potential in the small set of results I had siumulated. I decided to slowly build out the original version, intended to only simulate single games at a time, into a larger, more extensive project, with the goal of being able to simulate the entire NHL regular season

### Era 3: AneX (Current)
AneStat solved the main problems in HSC, lack of generality and scale. However, running the project over the course of an active season raised another issue; manually updating data each morning to add all games played the previous night is a time consuming process. As a result, I began work on a 'successor version' of AneStat with the goal of automating data ingestion.

While a number of people had already written code to collect and organize data from the NHL API before, I opted not to consult them. As working on AneX has always been intended as a learning experience, I felt that I would gain more by building the entire pipeline myself. The only information I consulted other sources for was the exact URL for any API access point I wanted to use.

### Where AneX Stands Now
At the moment, the only data my model uses from the NHL API is play-by-plays for each regular season game (over the last 2 seasons).

AneX's modeling is in active development. I am currently in the planning stages of a few new models that are more conceptually strong. Instead of attempting to model goal differential as a function of all compiled team statistics, I am hoping to build a model that partitions statistics into meaningful subsets, each of which produces results that have some explainable significance.

# The Pipeline
AneX's data processing pipeline can be split into three main sections; ingestion, cleaning, and compilation.

## Ingestion


## Cleaning


## Compilation

In its current state, I consider AneX's data pipeline complete, but not final. It's complete in the sense that it has the capability to ingest play-by-play data from the NHL API and process it into a format that's easily usable by all of the completed modeling modules. The pipeline is not final in the sense that it will likely continue to change as new modeling modules are added. Very briefly:

- Ingestion will likely only be modified if the model expands to use new data outside of play-by-plays.
- Cleaning will likely only be modified if game metadata the algorithm currently removes from the raw data is added to the model.
- Compilation is the most subject to change, almost certainly being modified whenever new parameter sets are added into the model's run options.

# The Model
**Please note: the modeling of AneX is still under active development. Treat most modeling as experimental in this project unless otherwise stated.**

## Home Goal Differential Prediction

## Aggregate Statline Generation
Currently, I have two separate methods to generate aggregate statlines; a random sample from a multivariate normal distribution and discrete sampling.

### Multivariate Normal Distribution

### Discrete Sampling
